name: des-y6-imsim-analysis
channels:
  - conda-forge
dependencies:
  - arviz=0.21.0
  - asdf=4.1.0
  - astropy=7.0.1
  - blosc=1.21.6
  - bzip2=1.0.8
  - cfitsio=4.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - contourpy=1.3.1
  - corner=2.2.3
  - dask-core=2025.2.0
  - des-desmeds=0.9.18
  - des-despyastro=3.0.1
  - des-despyfits=3.0.0
  - des-despymisc=3.0.1
  - des-eastlake=0.8.2
  - des-easyaccess=1.4.12
  - des-montara=0.10.0
  - des-pixcorrect=3.1.5
  - des-pizza-cutter=0.9.2
  - des-pizza-cutter-metadetect=0.9.1
  - des-sxdes=0.3.0
  - des-y6utils=0.10.0
  - eigen=3.4.0
  - equinox=0.11.12
  - esutil=0.6.16
  - fftw=3.3.10=nompi_*
  - fitsio=1.2.5
  - flake8=7.1.2
  - galsim=2.7.0
  - galsim_extra=0.2.1
  - h5py=3.13.0=nompi_*
  - hdf5=1.14.3=nompi_*
  - healpy=1.18.0
  - healsparse=1.11.1
  - hilbertcurve=2.0.5
  - hpgeom=1.4.0
  - iminuit=2.30.1
  - ipykernel
  - ipython
  - jax=0.5.1
  - jaxlib=0.5.1
  - jaxtyping=0.2.36
  - jinja2=3.1.5
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - llvm-openmp=19.1.7
  - llvmlite=0.44.0
  - lsstdesc-coord=1.3.0
  - matplotlib=3.9.4
  - meds=0.9.17
  - metadetect=0.11.0
  - ngmix=2.3.2
  - numba=0.61.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - numpyro=0.17.0
  - openblas=0.3.29
  - opt_einsum=3.4.0
  - orjson=3.10.15
  - pandas=2.2.3
  - piff=1.5.1
  - pillow=11.1.0
  - pip=25.0.1
  - pixmappy=1.0.0
  - progressbar=2.5
  - psfex=0.4.1
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1=*_cpu
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pytables=3.10.2
  - pytest=8.3.5
  - pytest-xdist=3.6.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.3
  - ruff=0.9.9
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sep=1.2.1
  - setuptools=75.8.2
  - skyproj=2.0.0
  - snappy=1.2.1
  - spherematch=0.10.2
  - tqdm=4.67.1
  - treecorr=5.1.1
  - treegp=1.3.1
  - tzdata=2025a
  - ultraplot=1.50.1
  - xarray=2025.3.1
  - xarray-einstats=0.8.0
  - zstandard=0.19.0
  - zstd=1.5.7
